[package]
name = "regexlang-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.4.0"
clap = { version = "4.3.23", features = ["derive"] }
logos = "0.13.0"
peg = "0.8.2"
termion = "2.0.1"
